name: My First Workflow
on:
  push:
    branches:
    - "release"
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    steps:
    - name: echo the date
      run: echo "the current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{github.ref-name}}

  test_and_deploy:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_KEY: ${{secrets.openweathermap_api}}
    steps:
    #https://github.com/marketplace/actions/setup-java-jdk
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    #https://github.com/marketplace/actions/setup-maven
    -name: Setup Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2

    #https://github.com/marketplace/actions/checkout
    - name: Checkout the source
      uses: actions/checkout@v3

    - name: Run test
      run: mvn clean test

    #https://github.com/marketplace/actions/deploy-to-heroku
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.heroku_app_name}}
          heroku_email: ${{secrets.email}}
          branch: ${{github.ref-name}}